### PR TITLE
Adding to melted api config

### PR DESCRIPTION
**Pull request by josx**
Using config in Melted Api

### CODE REVIEW

**Comment by josx** [comment]
Depends on https://github.com/inaes-tic/mbc-common/pull/8

**Comment by xaiki** [comment]
This breaks tests.

Keep the env variables please

El lunes, 6 de mayo de 2013, José Luis Di Biase escribió:

> ## Using config in Melted Api
> 
> You can merge this Pull Request by running
> 
>   git pull https://github.com/inaes-tic/mbc-mosto melted-api-config
> 
> Or view, comment on, or merge it at:
> 
>   https://github.com/inaes-tic/mbc-mosto/pull/101
> Commit Summary
> - Adding to melted api config
> 
> File Changes
> - _M_ api/Melted.jshttps://github.com/inaes-tic/mbc-mosto/pull/101/files#diff-0(14)
> - _M_ drivers/mvcp/mvcp-driver.jshttps://github.com/inaes-tic/mbc-mosto/pull/101/files#diff-1(2)
> 
> Patch Links:
> - https://github.com/inaes-tic/mbc-mosto/pull/101.patch
> - https://github.com/inaes-tic/mbc-mosto/pull/101.diff

## 

Sent from Gmail Mobile

**Comment by josx** [comment]
In my local machine, test are passed OK.
In travis It is timeout error **Error: timeout of 30000ms exceeded**
@fabriciocosta @Lacrymology  Any clue about this?

**Comment by josx** [comment]
I have changed mbc-common to dev (Now travis gives another error, pass with node 0.10, not with 0.8 until now)

**Comment by josx** [comment]
Anyone knows how to restart a job in travis? 

https://travis-ci.org/inaes-tic/mbc-mosto/jobs/6943189

**Comment by josx** [comment]
Now pass test on node 0.8, please check and merge

**Comment by jmrunge** [comment]
After it finishes, if you are logged in, from the drop down menu

**Pull request merged**
