### PR TITLE
Fix the parameters of the mongo playlist driver, and expose the new methods to the generic one

### PR DESCRIPTION
**Pull request by Lacrymology**
Also rename `boundary` to `window` for time window. The length of the time window is called `span` for Time span

### CODE REVIEW

**Comment by jmrunge** [comment]
Please, modify PR according to the mail sent a few minutes ago by the list
and re-pull.

2013/4/11 Tomas Neme notifications@github.com

> ---
> 
> You can merge this Pull Request by running
> 
>   git pull https://github.com/inaes-tic/mbc-mosto Lacrymology/driver/playlists
> 
> Or view, comment on, or merge it at:
> 
>   https://github.com/inaes-tic/mbc-mosto/pull/45
> Commit Summary
> - setup functions for newly defined parameters
> - return span in validTimes
> - calculate from, to, span as necessary
> - don't set the boundaries in getBoundary
> - use the received span in start
> - overriding the boundaries is now optional
> - expose new playlist driver methods in generic driver
> 
> File Changes
> - _M_ drivers/playlists/mongo-driver.jshttps://github.com/inaes-tic/mbc-mosto/pull/45/files#diff-0(66)
> - _M_ drivers/playlists/playlists-driver.jshttps://github.com/inaes-tic/mbc-mosto/pull/45/files#diff-1(36)
> 
> Patch Links:
> - https://github.com/inaes-tic/mbc-mosto/pull/45.patch
> - https://github.com/inaes-tic/mbc-mosto/pull/45.diff

**Comment by Lacrymology** [comment]
did the changes and rebased to master

**Comment by Lacrymology** [comment]
ran the tests and fixed some things from them

**Comment by Lacrymology** [comment]
why was this closed and not merged?!

**Pull request merged**
