### PR TITLE
URGENT Playlist drivers tests

### PR DESCRIPTION
**Pull request by Lacrymology**
These tests aren't ready, but they DO fix an issue with the latest caspa which changed the way playlists' elements are created (before they were Medias, which was a mistake, now they're Pieces).

The consequence of all this, plus the way the backbone.io middlewares work, is that the pieces are now reaching us without _ids.

In this fix I use the media checksum instead of the piece id, but this might be wrong, since two pieces with same media but different filters will generate the same ID, and therefore the same XML filename, wihch I think will be very bad indeed.

### CODE REVIEW

**Comment by Lacrymology** [comment]
I don't know if the right move is to merge this as-is (tests pass and I think they're correct, they're just incomplete), or fix caspa, or what, really. but the fixes in the last two commits are necessary for mosto to work with current caspa

**Comment by jmrunge** [comment]
I think we should fix Caspa. This workaround is quite weak...

Enviado desde mi BlackBerry

-----Original Message-----

**Comment by pardo-bsso** [comment]
There's a PR at https://github.com/inaes-tic/mbc-caspa/pull/112 that generates unique ids for Pieces. ,Works for me...

**Comment by jmrunge** [comment]
Can be then discard this PR when
https://github.com/inaes-tic/mbc-caspa/issues/112 is merged?

2013/4/17 Adrián Pardini notifications@github.com

**Comment by pardo-bsso** [comment]
> Can be then discard this PR when
> https://github.com/inaes-tic/mbc-caspa/issues/112 is merged?

It's already merged, but I think @Lacrymology knows better if this is
to be closed.

**Comment by jmrunge** [comment]
@Lacrymology?

2013/4/17 Adrián Pardini notifications@github.com

**Comment by Lacrymology** [comment]
The PR can be closed, but I need to rebuild the test data and fix current code, I think

**Comment by jmrunge** [comment]
Ok, will delete PR then and fill an issue with this, ok?

2013/4/17 Tomas Neme notifications@github.com

**Comment by jmrunge** [comment]
Replaced by #66

**Pull request closed without merging**
