### PR TITLE
Add coverage with istanbul

### PR DESCRIPTION
**Pull request by Lacrymology**
Added a `coverage` make target, using https://github.com/gotwarlost/istanbul

### CODE REVIEW

**Comment by jmrunge** [comment]
Can we add a test (or setup into coverage) to see that our tests covers more than x percent of the code?

**Comment by xaiki** [comment]
we should run on coverage,
the target now is to get coverage up to at least 80%

On 16 September 2013 10:04, Juan Martin Runge notifications@github.comwrote:

> Can we add a test (or setup into coverage) to see that our tests covers
> more than x percent of the code?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/inaes-tic/mbc-mosto/pull/122#issuecomment-24507988
> .

## 

Niv Sardi

**Comment by Lacrymology** [comment]
I have a branch based on this AND the rewrite that gives >80% coverage except for playlists

The playlists tests are waiting for the caspa changes to be merged in, because they depend on model changes.

I don't know how to test for coverage

**Comment by xaiki** [comment]
you can parse the coverage output.
or even better, dump the output to a file, and have an end target that
parse it (so we can still detect failures).

On 16 September 2013 11:37, Tomas Neme notifications@github.com wrote:

> I have a branch based on this AND the rewrite that gives >80% coverage
> except for playlists
> 
> The playlists tests are waiting for the caspa changes to be merged in,
> because they depend on model changes.
> 
> I don't know how to test for coverage
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/inaes-tic/mbc-mosto/pull/122#issuecomment-24514510
> .

## 

Niv Sardi

**Comment by Lacrymology** [comment]
But coverage is dumped AFTER the tests are run. It should be a different
command somehow

On Mon, Sep 16, 2013 at 1:35 PM, Niv Sardi notifications@github.com wrote:

> you can parse the coverage output.
> or even better, dump the output to a file, and have an end target that
> parse it (so we can still detect failures).
> 
> On 16 September 2013 11:37, Tomas Neme notifications@github.com wrote:
> 
> > I have a branch based on this AND the rewrite that gives >80% coverage
> > except for playlists
> > 
> > The playlists tests are waiting for the caspa changes to be merged in,
> > because they depend on model changes.
> > 
> > I don't know how to test for coverage
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/inaes-tic/mbc-mosto/pull/122#issuecomment-24514510>
> > .
> 
> ## 
> 
> Niv Sardi
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/inaes-tic/mbc-mosto/pull/122#issuecomment-24524231
> .

## 

"The whole of Japan is pure invention. There is no such country, there are
no such people" --Oscar Wilde

|_|0|_|
|_|_|0|
|0|0|0|

(__/)
(='.'=)This is Bunny. Copy and paste bunny
(")_(") to help him gain world domination.

**Comment by xaiki** [comment]
yep:
test: test-base test-blah test-coverage

test-base:
   $COVERITY --dump-to-file blah.log test test test

test-blah:
   do more tests

test-coverage:
   grep 80% blah.log || fail

On 16 September 2013 14:08, Tomas Neme notifications@github.com wrote:

> But coverage is dumped AFTER the tests are run. It should be a different
> command somehow
> 
> On Mon, Sep 16, 2013 at 1:35 PM, Niv Sardi notifications@github.com
> wrote:
> 
> > you can parse the coverage output.
> > or even better, dump the output to a file, and have an end target that
> > parse it (so we can still detect failures).
> > 
> > On 16 September 2013 11:37, Tomas Neme notifications@github.com
> > wrote:
> > 
> > > I have a branch based on this AND the rewrite that gives >80% coverage
> > > except for playlists
> > > 
> > > The playlists tests are waiting for the caspa changes to be merged in,
> > > because they depend on model changes.
> > > 
> > > I don't know how to test for coverage
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/inaes-tic/mbc-mosto/pull/122#issuecomment-24514510>
> > > .
> > 
> > ## 
> > 
> > Niv Sardi
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/inaes-tic/mbc-mosto/pull/122#issuecomment-24524231>
> > .
> 
> ## 
> 
> "The whole of Japan is pure invention. There is no such country, there are
> no such people" --Oscar Wilde
> 
> |_|0|_|
> |_|_|0|
> |0|0|0|
> 
> (__/)
> (='.'=)This is Bunny. Copy and paste bunny
> (")_(") to help him gain world domination.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/inaes-tic/mbc-mosto/pull/122#issuecomment-24526657
> .

## 

Niv Sardi

**Comment by jmrunge** [comment]
I think @xaiki's idea is good.  If it is ok with you two, I will merge this PR, then we will focus on @Lacrymology's branch (the one that gets 80% of coverage) and after merging it, add the coverage test the way @xaiki told.

**Comment by Lacrymology** [comment]
I'm not doing this now. Merge this and add an issue, you can give it high priority, but until we actually DO have 80% coverage, this will kill travis.

We can do it after this, melted-node's PR, the rewrite, and my test fixes are merged into master

**Comment by jmrunge** [comment]
Im ok with this.  @xaiki ?

**Comment by xaiki** [comment]
we talked it up.
ok, but make sure as soon as we have 80% coverage, we activate this.
(we can actually do it in a branch and merge it later).

On 24 September 2013 23:16, Juan Martin Runge notifications@github.comwrote:

> Im ok with this. @xaiki https://github.com/xaiki ?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/inaes-tic/mbc-mosto/pull/122#issuecomment-25057897
> .

## 

Niv Sardi

**Comment by Lacrymology** [comment]
This passes locally... =/

**Comment by Lacrymology** [comment]
and a while ago, in travis the 0.10 job was failing, and now the 0.8 job is failing

**Pull request merged**
