### PR TITLE
Jmrunge/issue#1

### LINKED ISSUE #1: Reloading playlists error
When Mosto receives the notification from the driver that the playlists have been updated, it reloads them, but does not delete or update the ones in memory, it just adds new playlists, resulting in a duplication of playlists.

### PR DESCRIPTION
**Pull request by jmrunge**
This pull request fixes #1 with the limitation that it only updates the in memory playlists, it does not sync with melted for the moment.  This will need more work and should be taken care on another issue.

### CODE REVIEW

**Comment by xaiki** [comment]
Fabricio , Cristian, please review.

Niv sardi

**Comment by Lacrymology** [comment]
shouldn't the commits be sign-off'ed?

**Comment by jmrunge** [comment]
Tomas,
When I run this on my machine

_git log --show-signature_

I get this:

*commit df0ed2569e0179fa7ca4a3cb14396d632e9f4a60
gpg: Firmado el mar 26 mar 2013 00:51:28 ART usando clave RSA ID 63A1E828
gpg: Firma correcta de "Juan Martin Runge jmrunge@gmail.com"
Author: Juan Martin Runge jmrunge@gmail.com
Date:   Tue Mar 26 00:51:28 2013 -0300

```
Fixed error when updating playlists that resulted in duplication*
```

But I dont see this in github... What I am doing wrong? Is there a special
way to push when commits are signed off?

Any help would be appreciated!

Juan

2013/3/26 Tomas Neme notifications@github.com

**Comment by xaiki** [comment]
On 26 March 2013 23:51, jmrunge notifications@github.com wrote:

> But I dont see this in github... What I am doing wrong? Is there a special
> way to push when commits are signed off?

when you commit do commit -s
it adds 'text' to the commit message.

## 

Niv Sardi

**Comment by jmrunge** [comment]
Im doing commit -sm... Isnt this right?

2013/3/27 Niv Sardi notifications@github.com

**Comment by jmrunge** [comment]
Well, after some tests, it seems I have to commit -sS and edit the message
from the commit, instead of using -sm and specifying the message inline.
Was the only combination that working for sign-off message (which is shown
on github) and gpg signature (which is NOT shown on github).

Thanks!

Juan

2013/3/27 Juan Martin Runge jmrunge@gmail.com

> Im doing commit -sm... Isnt this right?
> 
> 2013/3/27 Niv Sardi notifications@github.com
>

**Comment by xaiki** [comment]
I'm doing -sm and it works for me ©

## 

Niv Sardi

**Comment by xaiki** [comment]
you should really learn to use git rebase -i 
please flush your fixes where they belong.
there is no need to clutter history with bugs.

**Comment by jmrunge** [comment]
All fixes included in this brach are relevant to the issue... I didnt fixed
nor commited anything here that dont belong here.  Please tell me which
commit you think should go elsewhere...

2013/3/27 Niv Sardi notifications@github.com

**Comment by xaiki** [comment]
man git rebase.
all the 'fixed blah' commits should be squashed to the things they actually fix.
a feature branch and a fix branch shouldn't interfere.

implement foo
implement bar
implement baz
fix foo
fix bar
fix foo again
fix baz

is not an acceptable history.

**Comment by jmrunge** [comment]
Ok, so the problem is how am I writing my commit messages.  Because this
fixes are on the implementations done before... Or are you saying I should
commit a buggy branch and the write the fixes?  How can I fix something I
just implemented?  Or should I wait for everything on the branch to work
and make a huge commit... Im trying to follow you, but Im not getting
something...

2013/3/27 Niv Sardi notifications@github.com

**Comment by jmrunge** [comment]
Merging to let Tomas start working

**Pull request merged**
