### PR TITLE
URGENT Playlist driver fix and tests

### PR DESCRIPTION
**Pull request by Lacrymology**
This replaces #64

### CODE REVIEW

**Comment by Lacrymology** [comment]
The build fail because of #68 =(

**Comment by Lacrymology** [comment]
also https://github.com/inaes-tic/mbc-mosto/commit/b2f0029961c31cb4179f249bfffb0b18220c693d#commitcomment-3039384

**Comment by Lacrymology** [comment]
Fixes #66

**Comment by jmrunge** [comment]
Is this for merge or not? Im confused with your comments...

**Comment by Lacrymology** [comment]
It is, as far as I'm concerned. I'm just explaining why are these failing.

I think we should be calling `delete` on any newly created objects (specially mosto instances) in our tests' `after` hooks

**Comment by jmrunge** [comment]
Do you think this will fix our problem...? I think the problem is Mocha
running tests in parallel (sometimes), not cleaning our objects at the end
of the tests...

2013/4/18 Tomas Neme notifications@github.com

**Comment by Lacrymology** [comment]
The mocha people say tests aren't ever supposed to be run in parallel. If that's happening, they say we might be missing some done() somewhere. I don't think so.

The problem I **did** see in test is that a `mosto` instance from another breaks when I send pubsub messages on my tests. So thinking about it, and assuming what they say is true, I thought, well, this other mosto instance is still alive, because the garbage collector didn't get to it yet, as well as it's playlist driver, and it's callbacks are still set up, and that's why it breaks.. it's the OTHER instance that breaks, not the one in my test.

**Comment by jmrunge** [comment]
Well, I added some console.log to my tests a few days ago to see what
happened here and I saw them appearing in paralell, that is, the second
test printed out his console.log just one milli after the first test
printed his.  If that is not paralell, I dont know what to think... As for
the done() calls, if you miss one done() you get timeout error, so I dont
know how could we be missing one...

2013/4/18 Tomas Neme notifications@github.com

**Comment by Lacrymology** [comment]
This might have to do with your tests being badly structured.

I said something over gtalk, but you should have a
describe(describe(describe())describe()describe(describe()))-type tree
structure in your tests, this **might** have something to do about it

**Comment by jmrunge** [comment]
I have at most describe(describe(it()it()it())describe(it()it())) type
tree... As suggested by mocha...

2013/4/18 Tomas Neme notifications@github.com

**Comment by Lacrymology** [comment]
I've seen some of your tests with no root-level `describe()`, that's what I was talking about.

I didn't know they didn't recommend more than two-level trees.

**Comment by jmrunge** [comment]
Well, I never read "dont do this!", but in their examples (at least the
ones I saw) there were only 2 levels describe->describe->it

Which test of mine was without root? I should have made a mistake there!

2013/4/18 Tomas Neme notifications@github.com

**Comment by Lacrymology** [comment]
mosto-status, I think.

And I'm pretty sure you can have any depth level you want in your tests

**Comment by jmrunge** [comment]
Ok, will take a look at it...

2013/4/18 Tomas Neme notifications@github.com

**Comment by jmrunge** [comment]
@fabriciocosta fixed my test... Is ok to merge this before merging #69 ?

**Comment by Lacrymology** [comment]
I think it's better to merge #69 first because @fabriciocosta also fixed this bug in his branch, I believe.

I can work out the conflict after that is done

**Comment by jmrunge** [comment]
Ok, lets put this on hold then...

Enviado desde mi BlackBerry

-----Original Message-----

**Comment by Lacrymology** [comment]
Bump

**Comment by xaiki** [comment]
Delete.
Check for done.
Check tree.

**Comment by Lacrymology** [comment]
wat?

is that supposed to mean that this is already merged? git begs to disagree:

```
lacrymology@Roller:~/workspace/nodejs/inaes/mbc-mosto$ git diff --name-only master 
drivers/playlists/mongo-driver.js
test/playlist-mongo-driver.js
test/playlists/db-data.js
```

**Comment by xaiki** [comment]
Try delete()
Check we call done()
Check the call trees...

**Pull request merged**
