### PR TITLE
don't ignore mocha, it's ... our tests

### PR DESCRIPTION
**Pull request by xaiki**
Signed-off-by: Niv Sardi xaiki@evilgiggle.com

### CODE REVIEW

**Comment by csrocha** [comment]
@xaiki ... We must if an error happens, because mocha still running we must kill it at the end. Remember: make ignore errors if you prefix with '-' and continue execution.

**Comment by jmrunge** [comment]
@csrocha Are you saying we should ignore test errors? If we do, travis is useless.  Because it thinks tests pass.  Or at least that is what we saw in Tom tests (shouldnt have passed and travis marked the build as ok).

**Comment by Lacrymology** [comment]
why did you close this? This makes travis mark patches as passed even when tests fail!

**Comment by jmrunge** [comment]
Wasnt it merged??? I read "Merged" in last comment...

Enviado desde mi BlackBerry

-----Original Message-----

**Pull request merged**
